// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dmarins/gcp-cloud-run-challenge-go/internal/infrastructure/web/handlers"
	"github.com/dmarins/gcp-cloud-run-challenge-go/internal/usecase"
)

// Injectors from wire.go:

func NewGetWeatherByZipcodeUseCase() *usecase.GetWeatherByZipcodeUseCase {
	getWeatherByZipcodeUseCase := usecase.NewGetWeatherByZipcodeUseCase()
	return getWeatherByZipcodeUseCase
}

func NewWeatherHttpHandler(getWeatherByZipcodeUseCase usecase.GetWeatherByZipcodeUseCase) *handlers.WeatherHttpHandler {
	weatherHttpHandler := handlers.NewWeatherHttpHandler(getWeatherByZipcodeUseCase)
	return weatherHttpHandler
}
